/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author ahmed
 *///
import java .util.Stack;
public class calc extends javax.swing.JFrame {

    /**
     * Creates new form calc
     */
    public calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        set0 = new javax.swing.JButton();
        set1 = new javax.swing.JButton();
        set2 = new javax.swing.JButton();
        set3 = new javax.swing.JButton();
        set4 = new javax.swing.JButton();
        set5 = new javax.swing.JButton();
        set6 = new javax.swing.JButton();
        set7 = new javax.swing.JButton();
        set8 = new javax.swing.JButton();
        set9 = new javax.swing.JButton();
        set10 = new javax.swing.JButton();
        set11 = new javax.swing.JButton();
        set12 = new javax.swing.JButton();
        set13 = new javax.swing.JButton();
        set14 = new javax.swing.JButton();
        set15 = new javax.swing.JButton();
        set16 = new javax.swing.JButton();
        set17 = new javax.swing.JButton();
        set18 = new javax.swing.JButton();
        set19 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        set0.setText("0");
        set0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set0ActionPerformed(evt);
            }
        });

        set1.setText("1");
        set1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set1ActionPerformed(evt);
            }
        });

        set2.setText("2");
        set2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set2ActionPerformed(evt);
            }
        });

        set3.setText("3");
        set3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set3ActionPerformed(evt);
            }
        });

        set4.setText("4");
        set4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set4ActionPerformed(evt);
            }
        });

        set5.setText("5");
        set5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set5ActionPerformed(evt);
            }
        });

        set6.setText("6");
        set6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set6ActionPerformed(evt);
            }
        });

        set7.setText("7");
        set7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set7ActionPerformed(evt);
            }
        });

        set8.setText("8");
        set8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set8ActionPerformed(evt);
            }
        });

        set9.setText("9");
        set9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set9ActionPerformed(evt);
            }
        });

        set10.setText("+/-");
        set10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set10ActionPerformed(evt);
            }
        });

        set11.setText(".");
        set11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set11ActionPerformed(evt);
            }
        });

        set12.setText("/");
        set12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set12ActionPerformed(evt);
            }
        });

        set13.setText("x");
        set13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set13ActionPerformed(evt);
            }
        });

        set14.setText("-");
        set14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set14ActionPerformed(evt);
            }
        });

        set15.setText("+");
        set15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set15ActionPerformed(evt);
            }
        });

        set16.setText("=");
        set16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set16ActionPerformed(evt);
            }
        });

        set17.setText("c");
        set17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set17ActionPerformed(evt);
            }
        });

        set18.setText("del");
        set18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set18ActionPerformed(evt);
            }
        });

        set19.setText("√x");
        set19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(set4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(set8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(set9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(set18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(set5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(set6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(set15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(set2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(set3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(set14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(set0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(set11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(set13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(set16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(set17, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(set19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(set12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(set5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(set4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(set6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(set15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set0, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Stack<String> s=new Stack<>();
    double num1;
double num2;
double result;
String opperation;
//Stack lol =new Stack();
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void set0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set0ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"0");
    }//GEN-LAST:event_set0ActionPerformed

    private void set1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set1ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"1");
    }//GEN-LAST:event_set1ActionPerformed

    private void set2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set2ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"2");
    }//GEN-LAST:event_set2ActionPerformed

    private void set3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set3ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText(jTextField1.getText()+"3");
    }//GEN-LAST:event_set3ActionPerformed

    private void set4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set4ActionPerformed
        // TODO add your handling code here:
 jTextField1.setText(jTextField1.getText()+"4");
    }//GEN-LAST:event_set4ActionPerformed

    private void set5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set5ActionPerformed
        // TODO add your handling code here:
       jTextField1.setText(jTextField1.getText()+"5");
    }//GEN-LAST:event_set5ActionPerformed

    private void set6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set6ActionPerformed
        // TODO add your handling code here:
 jTextField1.setText(jTextField1.getText()+"6");
    }//GEN-LAST:event_set6ActionPerformed

    private void set7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set7ActionPerformed
        // TODO add your handling code here:
 jTextField1.setText(jTextField1.getText()+"7");
    }//GEN-LAST:event_set7ActionPerformed

    private void set8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set8ActionPerformed
        // TODO add your handling code here:
 jTextField1.setText(jTextField1.getText()+"8");
    }//GEN-LAST:event_set8ActionPerformed

    private void set9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set9ActionPerformed
        // TODO add your handling code here:
 jTextField1.setText(jTextField1.getText()+"9");
    }//GEN-LAST:event_set9ActionPerformed

    private void set10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set10ActionPerformed
        // TODO add your handling code here:
 jTextField1.setText((Double.parseDouble(jTextField1.getText())*-1)+"");
    }//GEN-LAST:event_set10ActionPerformed

    private void set11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set11ActionPerformed
        // TODO add your handling code here:
jTextField1.setText(jTextField1.getText()+".");
    }//GEN-LAST:event_set11ActionPerformed

    private void set15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set15ActionPerformed
        // TODO add your handling code here:
        num1= Double.parseDouble(jTextField1.getText());
      s.add(num1+"");
        opperation="+";
        s.add("+");
       jTextField1.setText("");
       
    }//GEN-LAST:event_set15ActionPerformed

    private void set16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set16ActionPerformed
    
        num2=  Double.parseDouble(jTextField1.getText());
         s.add(num2+"");//num2= Double.parseDouble(s.pop());
        
         
         
         for(int i=1;i<s.toArray().length;i+=2){
          
         if(s.get(i).equals("*")){
            
             num1= Double.parseDouble(s.get(i-1));
           num2= Double.parseDouble(s.get(i+1));
           s.remove(i-1);
           s.remove(i-1);
           s.remove(i-1);
           s.add(i-1, (num1*num2)+"");
             
             i-=2;
         }
             
         else if(s.get(i).equals("/")){
           
             num1= Double.parseDouble(s.get(i-1));
           num2= Double.parseDouble(s.get(i+1));
            if(num2==0)
                jTextField1.setText("you can't divide by zero");
            else{
           s.remove(i-1);
           s.remove(i-1);
           s.remove(i-1);
           s.add(i-1, (num1/num2)+"");
             
             i-=2;
         }
         }
         }
          
         for(int i=1;i<s.toArray().length;i+=2){
             
         if(s.get(i).equals("+")){
           
             num1= Double.parseDouble(s.get(i-1));
           num2= Double.parseDouble(s.get(i+1));
           
           s.remove(i-1);
           s.remove(i-1);
           s.remove(i-1);
           s.add(i-1, (num1+num2)+"");
             
             i-=2;
                     
         }
         else if(s.get(i).equals("-")){
             
             num1= Double.parseDouble(s.get(i-1));
           num2= Double.parseDouble(s.get(i+1));
           
           s.remove(i-1);
           s.remove(i-1);
           s.remove(i-1);
           s.add(i-1, (num1-num2)+"");
            
             i-=2;
                     
         }
         }
        
         jTextField1.setText(s.pop());
          /* for(int i=1;i<s.toArray().length;i+=2){
            
         if(s.get(i).equals("+")){
            
             num1= Double.parseDouble(s.get(i-1));
           num2= Double.parseDouble(s.get(i+1));
           s.remove(i-1);
           s.remove(i-1);
           s.remove(i-1);
           s.add(i-1, (num1+num2)+"");
             System.out.println(s.toString());
             i-=2;
         }
          if(s.get(i).equals("-")){
            
             num1= Double.parseDouble(s.get(i-1));
           num2= Double.parseDouble(s.get(i+1));
           s.remove(i-1);
           s.remove(i-1);
           s.remove(i-1);
           s.add(i-1, (num1-num2)+"");
             System.out.println(s.toString());
             i-=2;
         }
         
         }*/
       //  jTextField1.setText(s.pop());
       
        // while(!s.isEmpty()){
         
        // }
        /*
         opperation=s.pop();
         if(opperation.equals("*")){
             num1= Double.parseDouble(s.pop());
             result=num1*num2;
             jTextField1.setText(result+"");
         opperation="";
         num2=result;
         }
         if(opperation.equals("*")){
             if(num2==0)
                 jTextField1.setText("you can't divide by zero");
             else{
             num1= Double.parseDouble(s.pop());
             result=num1/num2;
             jTextField1.setText(result+"");
         opperation="";
         num2=result;
             }
         }
         if(opperation.equals("+")){
             num1= Double.parseDouble(s.pop());
             result=num1+num2;
             jTextField1.setText(result+"");
         opperation="";
         num2=result;
         }
         if(opperation.equals("-")){
             num1= Double.parseDouble(s.pop());
             result=num1-num2;
             jTextField1.setText(result+"");
         opperation="";
         num2=result;
         }
         */
       
    }//GEN-LAST:event_set16ActionPerformed

    private void set17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set17ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        s.removeAllElements();
    }//GEN-LAST:event_set17ActionPerformed

    private void set18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set18ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText().substring(0, jTextField1.getText().length()-1));
    }//GEN-LAST:event_set18ActionPerformed

    private void set19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set19ActionPerformed
        // TODO add your handling code here:
        num1=Math.sqrt( Double.parseDouble(jTextField1.getText()));
        jTextField1.setText(num1+"");
    }//GEN-LAST:event_set19ActionPerformed

    private void set14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set14ActionPerformed
        // TODO add your handling code here:
         num1= Double.parseDouble(jTextField1.getText());
      s.add(num1+"");
        opperation="-";
        s.add("-");
       jTextField1.setText("");
    }//GEN-LAST:event_set14ActionPerformed

    private void set13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set13ActionPerformed
        // TODO add your handling code here:
         num1= Double.parseDouble(jTextField1.getText());
s.add(num1+"");
        opperation="*";
        s.add("*");
       jTextField1.setText("");  
    }//GEN-LAST:event_set13ActionPerformed

    private void set12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set12ActionPerformed
        // TODO add your handling code here:
          num1= Double.parseDouble(jTextField1.getText());
      s.add(num1+"");
        opperation="+";
        s.add("/");
       jTextField1.setText("");;
    }//GEN-LAST:event_set12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton set0;
    private javax.swing.JButton set1;
    private javax.swing.JButton set10;
    private javax.swing.JButton set11;
    private javax.swing.JButton set12;
    private javax.swing.JButton set13;
    private javax.swing.JButton set14;
    private javax.swing.JButton set15;
    private javax.swing.JButton set16;
    private javax.swing.JButton set17;
    private javax.swing.JButton set18;
    private javax.swing.JButton set19;
    private javax.swing.JButton set2;
    private javax.swing.JButton set3;
    private javax.swing.JButton set4;
    private javax.swing.JButton set5;
    private javax.swing.JButton set6;
    private javax.swing.JButton set7;
    private javax.swing.JButton set8;
    private javax.swing.JButton set9;
    // End of variables declaration//GEN-END:variables
}
